spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/prototype_reservation
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: temporary
      password: temporary
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop

  flyway:
    enabled: false