spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/prototype_reservation
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: temporary
      password: temporary
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: build/generated/schema.sql
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      enabled: true
  flyway:
    enabled: false