spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/prototype_reservation
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: temporary
      password: temporary

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    username: temporary
    password: temporary
    driver-class-name: com.mysql.cj.jdbc.Driver
    table: flyway_version_control
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    url: jdbc:mysql://localhost:3306/prototype_reservation
    schemas: flyway

  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
