spring:
    config:
        import: "classpath:hibernate.yaml"
        activate:
            on-profile: production
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
