spring:
    config:
        activate:
            on-profile: stage
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: validate
            datasource:
                hikari:
                driver-class-name: com.p6spy.engine.spy.P6SpyDriver