spring:
    config:
        activate:
            on-profile: temporary
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate
    datasource:
        hikari:
            driver-class-name: com.p6spy.engine.spy.P6SpyDriver
            username: temporary
            password: temporary
            jdbc-url: jdbc:mysql://localhost:3306/prototype_reservation?serverTimezone=UTC&characterEncoding=UTF-8
