spring:
    config:
        activate:
            on-profile: temporary
    jpa:
        database-platform: rg.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
    datasource:
        hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/your_database?serverTimezone=UTC&characterEncoding=UTF-8
        username: temporary
        password: temporary
