- name: chore
  color: 'BFDADC'
  description: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
- name: docs
  color: '0075CA'
  description: 문서 수정
- name: feat
  color: '0E8A16'
  description: 새로운 기능을 추가
- name: refactor
  color: 'C5DEF5'
  description: 코드 리팩토링
- name: revert
  color: 'FBCA04'
  description: 커밋 혹은 변경사항 취소
- name: fix
  color: 'D73A4A'
  description: 버그 수정
- name: hotfix
  color: 'B60205'
  description: 급하게 치명적인 버그를 고쳐야하는 경우
- name: style
  color: 'EDEDED'
  description: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
- name: test
  color: '5319E7'
  description: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음


- name: conflict
  color: 'EF9263'
  description: Pull Request 충돌


- name: size/XS
  color: 'C5F7D0'
  description: < 10 lines
- name: size/S
  color: '9AE6B4'
  description: 10–29 lines
- name: size/M
  color: '68D391'
  description: 30–99 lines
- name: size/L
  color: 'F6E05E'
  description: 100–499 lines
- name: size/XL
  color: 'F6AD55'
  description: 500–999 lines
- name: size/XXL
  color: 'F56565'
  description: ≥ 1000 lines