coverage:
  ignore:
    - "**/entity/**"
    - "**/repository/**"
    - "**/persistence/**"
    - "**/jpa/**"
    - "**/config/**"
    - "**/*Properties"
    - "**/request/*"
    - "**/response/*"
    - "**/enumerations/*"
    - "**/exceptions/*"
    - "**/utilities/*"
    - "**/template/*"
    - "**/config*/*"