coverage:
  ignore:
    - "**/entity/**"
    - "**/repository/**"
    - "**/persistence/**"
    - "**/jpa/**"
    - "**/redis/**"
    - "**/config/**"
    - "**/*Properties"
    - "**/request/**"
    - "**/response/**"
    - "**/enumerations/**"
    - "**/exceptions/**"
    - "**/utilities/**"
    - "**/template/**"
    - "**/config*/**"
    - "**/test/**"