services:
  mysql:
    container_name: mysql-master
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=prototype_reservation'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_REPLICATION_MODE=master'
      - 'MYSQL_REPLICATION_USER=replicator'
      - 'MYSQL_REPLICATION_PASSWORD=replicator_pass'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql/master.cnf:/etc/mysql/mysql.conf.d/master.cnf:ro
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=prototype_reservation
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pverysecret"]
      interval: 10s
      timeout: 5s
      retries: 5
  mysql-replica:
    container_name: mysql-replica
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=prototype_reservation'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_REPLICATION_MODE=slave'
      - 'MYSQL_REPLICATION_USER=replicator'
      - 'MYSQL_REPLICATION_PASSWORD=replicator_pass'
      - 'MYSQL_MASTER_HOST=mysql-master'
      - 'MYSQL_MASTER_PORT_NUMBER=3306'
      - 'MYSQL_MASTER_ROOT_PASSWORD=verysecret'
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_replica_data:/var/lib/mysql
      - ./mysql/replica.cnf:/etc/mysql/mysql.conf.d/replica.cnf:ro
    command: --server-id=2 --relay-log=mysql-relay-bin --log-bin=mysql-bin --binlog-do-db=prototype_reservation
    networks:
      - mysql-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pverysecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-master:
    container_name: redis-master
    command: redis-server --appendonly yes
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./redis/master-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-replica-1:
    container_name: redis-replica-1
    command: redis-server --appendonly yes --replicaof redis-master 6379
    image: 'redis:latest'
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - ./redis/replica1-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-replica-2:
    container_name: redis-replica-2
    command: redis-server --appendonly yes --replicaof redis-master 6379
    image: 'redis:latest'
    depends_on:
      - redis-master
    ports:
      - "6381:6379"
    volumes:
      - ./redis/replica2-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel/sentinel-1.conf:/etc/redis/sentinel.conf
      - ./redis/sentinel/data-1:/data
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-network
  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel/sentinel-2.conf:/etc/redis/sentinel.conf
      - ./redis/sentinel/data-2:/data
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-network
  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel/sentinel-3.conf:/etc/redis/sentinel.conf
      - ./redis/sentinel/data-3:/data
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-network


  kafka-1:
    image: 'confluentinc/cp-kafka:latest'
    hostname: kafka-1
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka-1:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # JMX for monitoring (optional)
      KAFKA_JMX_PORT: 19092
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka-1-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka-1:29092" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on: [ ]
  kafka-2:
    image: 'confluentinc/cp-kafka:latest'
    hostname: kafka-2
    ports:
      - "9093:9093"
      - "19093:19093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://kafka-2:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # JMX for monitoring (optional)
      KAFKA_JMX_PORT: 19093
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka-2-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka-2:29092" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on: [ ]
  kafka-3:
    image: 'confluentinc/cp-kafka:latest'
    hostname: kafka-3
    ports:
      - "9094:9094"
      - "19094:19094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-3:29092,PLAINTEXT_HOST://localhost:9094'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-3:29092,PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://kafka-3:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # JMX for monitoring (optional)
      KAFKA_JMX_PORT: 19094
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka-3-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka-3:29092" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on: [ ]
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka-1:29092,kafka-2:29092,kafka-3:29092'
      KAFKA_CLUSTERS_0_METRICS_PORT: 19092
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy



volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

networks:
  redis-network:
    driver: bridge
  mysql-network:
    driver: bridge



