services:
  mysql:
    container_name: mysql-master
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=prototype_reservation'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pverysecret"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-master:
    container_name: redis-master
    command: redis-server --appendonly yes
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./redis/master-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-replica-1:
    container_name: redis-replica-1
    command: redis-server --appendonly yes --replicaof redis-master 6379
    image: 'redis:latest'
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - ./redis/replica1-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-replica-2:
    container_name: redis-replica-2
    command: redis-server --appendonly yes --replicaof redis-master 6379
    image: 'redis:latest'
    depends_on:
      - redis-master
    ports:
      - "6381:6379"
    volumes:
      - ./redis/replica2-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel/sentinel-1.conf:/etc/redis/sentinel.conf
      - ./redis/sentinel/data-1:/data
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-network

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel/sentinel-2.conf:/etc/redis/sentinel.conf
      - ./redis/sentinel/data-2:/data
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-network

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel/sentinel-3.conf:/etc/redis/sentinel.conf
      - ./redis/sentinel/data-3:/data
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge