spring:
    config:
        import:
            - classpath:redis/datasource/local.yaml
            - classpath:redis/datasource/production.yaml
            - classpath:redis/datasource/stage.yaml
            - classpath:redis/datasource/temporary.yaml
            - classpath:redis/redisson/index.yaml
