spring:
    config:
        activate:
            on-profile: local
    data:
        redis:
            host: localhost
            port: 6379
            timeout: 5000ms
            lettuce:
              pool:
                  max-active: 8
                  max-idle: 8
                  min-idle: 0

