spring:
    activate:
        on-profile: local




http-interface:
    retry:
        max-attempts: 3
        initial-interval: 100
        multiplier: 2.0
        max-interval: 2000
    internal:
        time-table-occupancy: http://localhost:8080/api/v1/internal/timetable/{timeTableId}/occupancy/{timeTableOccupancyId}