name: "✨ Feature(Story)"
description: "새로운 기능 추가"
labels: [ "feat" ]
body:
  - type: dropdown
    attributes:
      label: 🚦 우선순위
      description: 이슈 우선순위를 선택하세요.
      options:
        - 낮음
        - 보통
        - 높음
        - 긴급
  - type: dropdown
    attributes:
      label: 🎫 유형
      description: issue의 유형을 선택
      options:
        - N/A
        - Epic
        - Story
        - Task
        - Sub-task
      default: 2
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      value: |
        ### 👤 UserStory
        - 역할(As a) :
        - 목적(I want to) :
        - 이유(So that) :
        - Acceptance Criteria(BDD) :
          - Scenario: 
              - Given : 
              - When : 
              - Then :
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
