name: "✨ Feature"
description: "새로운 기능 추가"
labels: [ "feat" ]
body:
  - type: dropdown
    attributes:
      label: 🚦 우선순위
      description: 이슈 우선순위를 선택하세요.
      options:
        - 낮음
        - 보통
        - 높음
        - 긴급
  - type: dropdown
    attributes:
      label: 🎫 유형
      description: issue의 유형을 선택
      options:
        - N/A
        - Epic
        - Story
        - Task
        - Sub-task
      default: 0
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
