spring:
    activate:
        on-profile: temporary

security:
    jwt:
        properties:
            expire-time: 300000
            secret: HELLO
            issuer: HELLO
        allowed:
            path: /**