spring:
  flyway:
    user: temporary
    password: temporary
    driver-class-name: com.mysql.cj.jdbc.Driver
    table: flyway_version_control
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration
    url:  jdbc:mysql://localhost:3306
    schemas: flyway