spring:
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    validate-on-migrate: true
    url: jdbc:mysql://mysql:3306/prototype-reservation
