spring:
    config:
        import:
            - classpath:kafka/local.yaml
            - classpath:kafka/production.yaml
            - classpath:kafka/stage.yaml
            - classpath:kafka/temporary.yaml