name: Adapter Module Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Run tests and coverage
        run: ./gradlew :application-module:test :application-module:jacocoTestReport
      - name: Upload application-module Jacoco
        uses: actions/upload-artifact@v4
        with:
          name: application-jacoco
          path: application-module/build/reports/jacoco/test/jacocoTestReport.xml
      - name: Upload adapter-module test result
        uses: actions/upload-artifact@v4
        with:
          name: application-test-results
          path: application-module/build/test-results/**/TEST-*.xml
