
name: Assign Codeowner to Issue
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const text = await github.rest.repos.getContent({
              ...context.repo,
              path: '.github/CODEOWNERS',
              mediaType: { format: 'raw' }
            });
            const lines = text.data.split('\n').filter(l => l.includes('@'));
            const owners = lines.flatMap(l => l.match(/@\w+/g)).map(u => u.replace('@', ''));
            if (owners.length) {
              await github.rest.issues.addAssignees({
                ...context.repo,
                issue_number: context.issue.number,
                assignees: [owners[0]]
              });
            }
