name: Upload Coverage to Codecov (on master only)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  coverage-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@c5195ef # v4.7.1
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9ef # v4.4.2

      - name: Gradle Caching
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Run all tests & generate coverage
        run: ./gradlew jacocoTestReport

      - name: Upload to Codecov
        uses: codecov/codecov-action@18283e0 # v5.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # 프라이빗 repo만 필요
          files: |
            **/jacocoTestReport.xml
          flags: all-modules
          name: codecov-master
          fail_ci_if_error: true