name: Sync Labels

on:
  push:
    paths:
      - .github/labels.yaml

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcb5dd907a8 # v5.0.0
      - uses: EndBug/label-sync@5207415 # v2.3.3
        with:
          config-file: .github/labels.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}