name: Mark stale issues and PRs
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정
permissions:
  contents: read
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "이 이슈는 최근 활동이 없어 stale 상태로 변경됩니다."
          stale-pr-message: "이 PR은 최근 활동이 없어 stale 상태로 변경됩니다."
          days-before-stale: 21
          days-before-close: 14
          repo-token: ${{ secrets.GITHUB_TOKEN }}