name: Pull Request CI
on:
    pull_request:
        branches:
            - master
            - main

permissions:
    id-token: write
    contents: read

jobs:
    adapter-module-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'corretto'
                    cache: gradle



            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Gradle Caching
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Grant execute permission to gradlew
                run: chmod +x ./gradlew
            -   name: test adapter-module with Gradle Wrapper
                run: ./gradlew :adapter-module:test --parallel
    application-module-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'corretto'
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Gradle Caching
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Grant execute permission to gradlew
                run: chmod +x ./gradlew

            -   name: test application-module with Gradle Wrapper
                run: ./gradlew :adapter-module:test --parallel


    build:
        runs-on: ubuntu-latest
        needs:
            - adapter-module-test
            - application-module-test
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'corretto'
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Gradle Caching
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Build with Gradle Wrapper
                run: ./gradlew build -x test
