name: Code Review

on:
    pull_request:
        types: [ opened, reopened, synchronize ]

permissions:
    pull-requests: write
    contents: read

jobs:
    review:
        if: "!contains(github.event.pull_request.title, '[NO_REVIEW]')"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

            -   name: ChatGPT Code Review
                uses: anc95/ChatGPT-CodeReview@763282a7d171b9a8224bb2590803eed11b918837 # main latest
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                    LANGUAGE: Korean
                    PROMPT: ${{secrets.OPENAI_PROMPT}}
                    MODEL: gpt-5-mini
                    TEMPERATURE: 0.3
                    MAX_TOKENS: 4096
                    IGNORE_PATTERNS: .github,.gradle/**/*,.gitignore,*.yaml,*.jar,.gitkeep
                    INCLUDE_PATTERNS: "*.kt,*.java"

