name: "Label PR by Size"


permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.0
        with:
          sizes: >
            {
             XS=0..9
             S=10..29
             M=30..99
             L=100..499
             XL=500..999
             XXL=1000..
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}