name: "Label PR by Size"


permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for existing size label
        id: check-size-label
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            return labels.some(name => name.startsWith('size/'));
          result-encoding: string

      - name: Remove existing size labels
        if: steps.check-size-label.outputs.result == 'true'
        uses: PauMAVA/add-remove-label-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          remove: size/XS, size/S, size/M, size/L, size/XL, size/XXL

      - uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
             "0": "XS",
             "50": "S",
             "150": "M",
             "500": "L",
             "1000": "XL",
             "3000": "XXL"
            }