name: Pull Request CI
on:
  pull_request:
    branches:
      - master
      - main

permissions:
  id-token: write
  contents: read
  checks: write  # ✅ Check Run 생성을 위해 반드시 필요
  pull-requests: write


concurrency:
  group: CI
  cancel-in-progress: true

jobs:
  ［CI］Adapter Module:
    uses: newkayak12/prototype-reservation-system/.github/workflows/adapter-module-test.yaml@master

  ［CI］Application Module:
    uses: newkayak12/prototype-reservation-system/.github/workflows/application-module-test.yaml@master

  ［CI］Core Module:
    uses: newkayak12/prototype-reservation-system/.github/workflows/core-module-test.yaml@master

  Publish Test Results:
    needs:
      - adapter-module-test
      - application-module-test
      - core-module-test
    uses: newkayak12/prototype-reservation-system/.github/workflows/publish-test-result.yaml@master

  Upload to SonarClouq:
    name: SonarCloud Scan
    needs:
      - adapter-module-test
      - application-module-test
      - core-module-test
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    uses: newkayak12/prototype-reservation-system/.github/workflows/upload-sonarcloud.yaml@master

  Upload to Codecov:
    name: Upload Coverage to Codecov
    needs:
      - adapter-module-test
      - application-module-test
      - core-module-test
    uses: newkayak12/prototype-reservation-system/.github/workflows/upload-codecov.yaml@master

  Build:
    name: Build
    needs:
      - adapter-module-test
      - application-module-test
      - core-module-test
    uses: newkayak12/prototype-reservation-system/.github/workflows/build.yaml@master
