name: Pull Request CI
on:
  pull_request:
    branches:
      - master
      - main

permissions:
  id-token: write
  contents: read
  checks: write  # ✅ Check Run 생성을 위해 반드시 필요
  pull-requests: write


concurrency:
  group: CI
  cancel-in-progress: true

jobs:
  adapter-module:
    name: Adapter Module Test
    uses: newkayak12/prototype-reservation-system/.github/workflows/adapter-module-test.yaml@master

  application-module:
    name: Application Module Test
    uses: newkayak12/prototype-reservation-system/.github/workflows/application-module-test.yaml@master

  core-module:
    name: Core Module Test
    uses: newkayak12/prototype-reservation-system/.github/workflows/core-module-test.yaml@master

  publish_test_results:
    name: Publish Test Results
    needs:
      - adapter-module
      - application-module
      - core-module
    uses: newkayak12/prototype-reservation-system/.github/workflows/publish-test-result.yaml@master

  upload_to_sonar_cloud:
    name: Upload JacocoReports to SonarCloud Scan
    needs:
      - adapter-module
      - application-module
      - core-module
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{secrets.SONAR_PROJECT_KEY}}
      SONAR_ORGANIZATION: ${{secrets.SONAR_ORGANIZATION}}
    uses: newkayak12/prototype-reservation-system/.github/workflows/upload-sonarcloud.yaml@master

  upload_to_codecov:
    name: Upload Coverage to Codecov
    needs:
      - adapter-module
      - application-module
      - core-module
    uses: newkayak12/prototype-reservation-system/.github/workflows/upload-codecov.yaml@master

  build:
    name: Build
    needs:
      - adapter-module
      - application-module
      - core-module
    uses: newkayak12/prototype-reservation-system/.github/workflows/build.yaml@master
