name: Conflict Label


on:
  pull_request:
    types: [synchronize, opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v3
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          dirtyLabel: "conflict"
          removeOnDirtyLabel: true
          commentOnDirty: true
          commentOnClean: true