name: Code Review

on:
    pull_request:
        types: [ opened, reopened, synchronize ]

permissions:
    pull-requests: write
    contents: read

jobs:
    review:
        if: "!contains(github.event.pull_request.title, '[NO_REVIEW]')"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: ChatGPT Code Review
                uses: anc95/ChatGPT-CodeReview@main
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                    LANGUAGE: Korean
                    PROMPT: ${{secrets.OPENAI_PROMPT}}
                    MODEL: gpt-5
                    TEMPERATURE: 0.3
                    MAX_TOKENS: 2048
                    IGNORE_PATTERNS: .github,.gradle/**/*,.gitignore,*.yaml,*.jar,.gitkeep
                    INCLUDE_PATTERNS: "*.kt,*.java"

