name: "Label PR by Size"


permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
             "0": "XS",
             "9":"S",
             "29":"M",
             "99":"L",
             "499":"XL",
             "999":"XXL"
            }