name: SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs:
      - adapter-module-test
      - application-module-test
      - core-module-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: corretto

      - name: Download adapter jacoco
        uses: actions/download-artifact@v3
        with:
          name: adapter-jacoco
          path: jacoco/adapter
      - name: Download application jacoco
        uses: actions/download-artifact@v3
        with:
          name: application-jacoco
          path: jacoco/application
      - name: Download core jacoco
        uses: actions/download-artifact@v3
        with:
          name: core-jacoco
          path: jacoco/core
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_org
            -Dsonar.sources=.
            -Dsonar.coverage.jacoco.xmlReportPaths=jacoco/adapter/jacocoTestReport.xml,jacoco/application/jacocoTestReport.xml,jacoco/core/jacocoTestReport.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}