name: TODO to Issue
on:
  push:
    branches: [main]

permissions:
  issues: write
  pull-requests: write

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - uses: alstr/todo-to-issue-action@c45b007d85c8edf3365b139a9d4c65793e7c674f # v4.16.4
