name: TODO to Issue
on:
  push:
    branches: [main]

permissions:
  issues: write
  pull-requests: write

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: alstr/todo-to-issue-action@v4
